### ISSUE TITLE
Unable to generate app with the same name twice

### ISSUE THREAD

**Issue by tbo** [triAGENS/ArangoDB#1220]
The application generation fails, if another application with the same name has been generated beforehand. To reproduce this execute this step twice (with the same name of course): https://www.arangodb.com/tutorial-foxx#new-application

I found the likely reason for this in the browser console:

500 Internal Server Error
```
A runtime error occurred while executing an action: [ArangoError 27: file exists] Error: file exists
  at Error (native)
  at [object Object]._.extend.write (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/apps/system/aardvark/lib/foxxTemplateEngine.js:24:10)
  at /Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/apps/system/aardvark/foxxTemplates.js:62:18
  at action.callback (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:125:9)
  at /Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/request_context.js:75:5
  at /Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/request_context.js:75:5
  at execute (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:977:7)
  at next (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:994:7)
  at [object Object]:386:5
  at execute (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:977:7)
  at next (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:994:7)
  at [object Object]:386:5
  at execute (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:977:7)
  at Object.routeRequest (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:998:3)
  at Function.actions.defineHttp.callback (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/actions/api-system.js:55:15)

This error was triggered by the following route {"path":"/_admin/aardvark/templates/generate","regexp":{},"prefix":false,"depth":4,"urlParameters":{},"callback":{"options":{},"methods":["DELETE","GET","HEAD","OPTIONS","POST","PUT","PATCH"]},"route":{"url":{"match":"/templates/generate","methods":["post"]},"action":{},"docs":{"parameters":[{"name":"configuration","paramType":"body","description":"The configuration for the template.","dataType":"configuration"}],"errorResponses":[],"httpMethod":"POST","nickname":"post_generate"},"context":"/templates"}}
```

**Comment by mchacki** [comment]
Should be fixed in next 2.4 release.
